[package]
name = "musicprogram"
version = "0.1.0"
authors = ["Filip Szczepański <jazz2rulez@gmail.com>"]
edition = "2018"
license = "ISC"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursive = "0.16.3"
jack = "0.7.0"
rtrb = "0.1.3"
wmidi = "4.0.6"
